### ISSUE TITLE
Android not building in recent React Native, need to use more recent SDKVersion and BuildTools

### ISSUE THREAD

**Issue by primordius** [anmoljain10/react-native-zebra-bluetooth-printer#32]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-zebra-bluetooth-printer@1.0.9` for the project I'm working on.

Was getting an error "AAPT: error: resource android:attr/lStar not found"

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-zebra-bluetooth-printer/android/build.gradle b/node_modules/react-native-zebra-bluetooth-printer/android/build.gradle
index bef73c4..12d6ee3 100644
--- a/node_modules/react-native-zebra-bluetooth-printer/android/build.gradle
+++ b/node_modules/react-native-zebra-bluetooth-printer/android/build.gradle
@@ -13,8 +13,8 @@ buildscript {
 apply plugin: 'com.android.library'
 
 android {
-    compileSdkVersion 28
-    buildToolsVersion "28.0.3"
+    compileSdkVersion 33
+    buildToolsVersion "33.0.0"
 
     defaultConfig {
         minSdkVersion 16
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by anmoljain10** [comment]
Hi @primordius , thanks for your contribution. We'll update the package with your fixes soon.

**Comment by anmoljain10** [comment]
Updated in v1.0.11
