### ISSUE TITLE
Promise takes at least 10 seconds to respond and print. (ANDROID)

### ISSUE THREAD

**Issue by pabmoroni** [anmoljain10/react-native-zebra-bluetooth-printer#35]
I send command to print the label, it takes too long (around 10 seconds) for the promise to return if label has been printed or not.
I need to print a large number of labels and it takes too long. Is there any way to pass the number of labels to print per promise?

I use version 1.0.11

Thanks!

**Comment by anmoljain10** [comment]
Can you check if version 1.0.12 solves your issue?
